### ISSUE TITLE
$grid shorthand with passed gutter breaks in libsass

### ISSUE THREAD

**Issue by lmartins** [ericam/susy#452] opened 2015-03-16 19:50 UTC
This is probably related with Libsass itself, but when I try to define a grid using the shorthand notation:
```sass
$grid: (1 2 .5 2 2 2 2 2 2) 0.25;
```
I get the following error back:
```
[19:49:30] gulp-notify: [Compile Error] Error in plugin 'gulp-sass'
Message:
    argument `$number` of `unitless($number)` must be a number
Backtrace:
	bower_components/susy/sass/susy/language/susy/_settings.scss:84, in function `unitless`
	bower_components/susy/sass/susy/language/susy/_settings.scss:84, in function `parse-layout`
	bower_components/susy/sass/susy/language/susy/_settings.scss:129, in function `if`
	bower_components/susy/sass/susy/language/susy/_settings.scss:129, in function `parse-grid`
	bower_components/susy/sass/susy/language/susy/_container.scss:12, in mixin `container`
	src/sass/render/regions/_main-content.scss:163, in mixin `@content`
	../wip-roots/sass/mdf/helpers/_layout.scss:29, in mixin `@content`
	bower_components/sass-mq/_mq.scss:219, in mixin `mq`
	../wip-roots/sass/mdf/helpers/_layout.scss:28, in mixin `desktop`
	src/sass/render/regions/_main-content.scss:156
Details:
    fileName: /Users/luismartins/Sites/webipack.dev/wp-content/themes/wip-booklet/bower_components/susy/sass/susy/language/susy/_settings.scss
    lineNumber: 84
```

Is this something I should report on Libsass instead?

**Comment by xzyfer** [comment] 2015-04-28 00:21
Hey @lmartins, this sounds like a Libsass issue.

Can please provide the node-sass/libsass version with `./node_modules/.bin/node-sass --version`?
Also i,f you could @debug the value being passed into `unitless` in `parse-layout` I can try to reproduce the issue in Libsass.

**Comment by lmartins** [comment] 2015-04-29 09:51
Hey @xzyfer, thanks for the feedback here.

I don't have a `node-sass` folder inside of `.bin`. Although im currently working on a project with this setup and it is compiling sass.

Not really sure what you mean by debugging the value being passed into unites. Could you please clarify this?

Thanks again.

**Comment by xzyfer** [comment] 2015-04-29 10:22
>Not really sure what you mean by debugging the value being passed into unites. Could you please clarify this?

I mean editing `bower_components/susy/sass/susy/language/susy/_settings.scss` and on the line before `unitless` is called add an `@debug()` statement with the value that is being passed into unitless.

**Comment by ericam** [comment] 2015-08-27 21:51
As far as I can tell, this seems to be working now. Closing, unless there are more details.

**Closed by ericam** 2015-08-27 21:51 UTC
