### ISSUE TITLE
Span mixin not outputting code

### ISSUE THREAD

**Issue by sir-dunxalot** [ericam/susy#469] opened 2015-04-26 21:36 UTC
I have a very strange issue using Susy 2.2.2. I am running a project with node sass inside an Ember.js project using [ember-cli-sass](https://github.com/aexmachina/ember-cli-sass). Node sass version is 3.0.0-beta.2.

I have susy imported and have confirmed some Susy mixins are working. For example, the following code works correctly:

```sass
.grid {
  @include container;
}
```

The `span` function *does* work. However, the `span` mixin is broken. The following does not output any code:

```sass
.third {
  @include span(4);
}
```

However, if I add a random snippet of code to the `span` mixin in the Susy source the grid code above works as intended:

```sass
@mixin span(
  $span
) {
  $inspect: $span;
  $span: parse-span($span);
  $output: span-math($span);
  $nesting: susy-get(span, $span);
  $clear: susy-get(clear, $span);

  $box: susy-get(box-sizing, $span);
  $content-box: if(susy-get(global-box-sizing) != 'border-box', true, false);
  $box: $box or if(is-inside($span) and $content-box, border-box, null);

  @if $clear == break {
    @include break;
  } @else if $clear == nobreak {
    @include nobreak;
  }

  background: transparent; // Added and now the grid displays correctly

  @include susy-inspect(span, $inspect);
  @include output((box-sizing: $box));
  @include float-span-output($output...);

  @if valid-columns($nesting, silent) {
    @include nested($span) { @content; }
  } @else {
    @content;
  }
}
```

**Comment by ericam** [comment] 2015-05-07 01:26
That is very odd. Have you tried upgrading to the stable `node-sass 3.0.0` release?

**Comment by sir-dunxalot** [comment] 2015-05-07 13:30
Thanks for the response. I have not because the node-sass version is embedded as an Ember addon (isolated JS plugin as an NPM module and compiled by a Node server) but I will fork it, change to the stable node-sass release, and report back.

**Comment by ericam** [comment] 2015-08-27 13:35
Can't reproduce. Closing until further updates.

**Closed by ericam** 2015-08-27 13:35 UTC
Labels: can't reproduce
