### ISSUE TITLE
Error "may only compare numbers"

### ISSUE THREAD

**Issue by gionkunz** [ericam/susy#434] opened 2015-02-12 15:11 UTC
With Susy 2.2.2, node-sass 2.0.1, lib-sass 3.1.0 compiled on 64bit linux (god, how I dislike this wrapper maintenance hell) I get the following error in the description when compiling a simple file like this:
```scss
.container {
  @include container(1000px);
  
  .column {
    @include span(20%);
  }
}
```

I tracked it down to the following trace: `span(span.scss:13) > span-math(span.scss:70) > get-gutters(gutters.scss:112) > get-gutter-width(gutters.scss:72)`

The problematic code is:
```scss
...
@if $_gutters and ($_gutters > 0) and not($_gutter) {
...
```

The problem is that somehow the `1/4` that is stored as number in the `$_gutters` variable is somehow not detected as number in the condition. Also in libsass the following applies:
```scss
$n1: 1/4; // Type is number and value is 0.25
$n-map: (
  n: 4
);
$n2: map-get($n-map, "n"); // Type is number and value is 1/4
```
This is kind of weird and is probably a bug in libsass.

I don't know how the 1/4 value gets into the `$_gutters` variable but probably you're extracting it from the settings map similarly which will result into the later case as shown above.

The following code is reproducing this issue (as 1/4 is not evaluated but stored as value). If you change from `$_gutters: #{1/4};` to `$_gutters: 1/4` the example will work as it will store 0.25 which will work in the condition.

```scss
$susy-defaults: (
  columns: 4,
  gutters: 1/4,
);
$_gutters: map-get($susy-defaults, "gutters");
$_gutter: null;

@debug "$_gutters type / value:";
@debug type-of($_gutters);
@debug $_gutters;
@debug "$_gutter type / value:";
@debug type-of($_gutter);
@debug $_gutter;

@if $_gutters and ($_gutters > 0) and not($_gutter) {
  @debug "TEST";
}
```

One hack to get around this issue is to use the `abs` function to wrap the weird `1/4 of type number`:
```scss
$susy-defaults: (
  columns: 4,
  gutters: 1/4,
);
$_gutters: abs(map-get($susy-defaults, "gutters"));
```
This will get 0.25 into `$_gutters`

Do you think I missed something? Can you reproduce the problems on your end?

**Comment by ericam** [comment] 2015-02-12 16:48
This is a known libsass bug. It was actually fixed and released several weeks ago, but `node-sass` has not updated to use that release. In the meantime, we should maybe update our default gutter setting.

**Comment by gionkunz** [comment] 2015-02-12 17:23
Yeah if you put `.25` into the defaults it would be a bit more friendly to the current node-sass version then. But then the next issue will come up ;-) It would be so awesome if there would be a Sass / SCSS specification where multiple vendors could implement a version according to those specifications... Would make all our lives so much easier

**Comment by michaelwarren1106** [comment] 2015-04-20 14:27
@ericam can you link to the version of libsass that has the fix for this? The updated release (3.1.0) is what node-sass and gulp-sass are currently using and I'm still getting this same error when trying to do

.container { @include container(100px); }
@include span(30%);

**Comment by ericam** [comment] 2015-04-21 05:06
Here's the closed issue from last year: https://github.com/sass/libsass/issues/590

**Comment by michaelwarren1106** [comment] 2015-04-21 12:50
This doesn't seem to help my situation, as

1) I'm not using a fraction and I'm not setting gutters, which every proposed solution describes
2) I'm using all the current versions of susy, gulp-sass, and libsass, which you say have fixed the issue.

So, I'm looking for a little help determining that the issue is indeed fixed, since I'd really like to be able to use susy.

Seems to me that this issue isn't fixed, though every issue on it is closed with the simple "just put parentheses around your fraction" answer.

I dont have a fraction to put parentheses around, and  putting parens around the percentage doesn't fix the issue.

Any ideas?

**Comment by ericam** [comment] 2015-04-21 16:41
Sure, I understand your confusion. I'm confused as well. But you are actually using a fraction without knowing it, *because* you are not setting gutters. The default gutter setting in susy is `1/4` which we were planning to change, but then it seemed to be fixed on the libsass end. If you do set your own gutters, the error will go away on your end.

Clearly, we have to open one of these issues again. I'm not sure what happened, because it certainly was working at one point. We'll have to look into that.

**Comment by michaelwarren1106** [comment] 2015-04-21 17:25
Thanks for reopening. For some more context, all I've tried to do is your quick start example:

For example:

.container { @include container(80em); }
.image { @include span(25%); }

Instead of 80em, though, I had 960px, but I got the "may only compare numbers" error regardless. Also setting our own gutters didnt seem to change anything either.

**Comment by michaelwarren1106** [comment] 2015-04-28 15:49
any updates on this issue? I'm in the process of evaluating using susy for my corporate UI Component Framework, so if it doesnt/cant be made to work with libsass, then we won't be able to move forward with susy. I'd love to be able to recommend it as a standard, but I can't until this issue is resolved.

Thanks!

**Comment by ericam** [comment] 2015-04-28 17:48
It is still the same libsass error. The bug was only partially fixed on their end. I will file a new issue there.

In the meantime, I released susy `2.2.3` which changes the default gutter setting from `1/4` to `.25` — which makes this code work for me.

**Comment by michaelwarren1106** [comment] 2015-04-28 20:15
thanks! susy 2.2.3 does indeed work for us!

**Comment by ericam** [comment] 2015-04-28 20:16
glad to hear it!

**Closed by ericam** 2015-04-28 20:16 UTC

**Comment by ciscoo** [comment] 2015-04-29 15:15
Was just running into this issue as well, 2.2.3 works for me over here. :thumbsup:

**Comment by suprahfly** [comment] 2015-05-17 09:31
Sadly this doesn't help when you need a static pixel value for gutters.

**Comment by ericam** [comment] 2015-05-19 16:05
@suprahfly I'm not sure what you mean. What settings are you using, and what error are you getting?

**Comment by heyalbert** [comment] 2015-11-04 10:47
I'm runing into the same error. I'm using em.

**Comment by ericam** [comment] 2015-11-04 16:41
@heyalbert using `em` for what? You'll need to provide a lot more detail for anyone to help you track this down. Unless you are using an old version of libsass, it's not likely that you are actually having the same issue as others here.
