### ISSUE TITLE
Passing asymmetrical to inner grids

### ISSUE THREAD

**Issue by lmartins** [ericam/susy#464] opened 2015-03-27 21:02 UTC
Im trying to build a layout where I have inner layouts with specific settings.

I've tried a few different solutions but im getting a bit confused about the best approach to achieve this.

Here's what i've tried.
```
.element{
        $layout: 12 fluid after 0.2;
        .entry{
            @include gallery(1 $layout);
        }
    }
```

This one retrieves:
```
[21:00:23] gulp-notify: [Compile Error] Error in plugin 'gulp-sass'
Message:
    invalid null operation: ""0" plus null".
```

While trying to using the layout mixin:
```
.element{
        @include layout((3 3 3) fluid after .03);
        .entry{
            @include gallery(1);
        }
    }
```

Im getting:
```
[21:01:19] gulp-notify: [Compile Error] Error in plugin 'gulp-sass'
Message:
    index out of bounds for `nth($list, $n)`
```

Im most likely misunderstanding the docs and doing something wrong, if you help me out understating would be fantastic.

Thanks again.

**Comment by zellwk** [comment] 2015-03-31 02:20
this should help: 
http://www.zell-weekeat.com/asymmetric-layouts-with-susy/

**Comment by ericam** [comment] 2015-08-27 14:11
Your first example has syntax problems. You either need to parse the layout shorthand (`layout(12 fluid after 0.2)`), or join the shorthand list with the existing argument (`@include gallery(join((1), $layout));`). Clearly that second option is ugly, but this is just a matter of how Sass understands nested lists.

The second issue I can't reproduce, but it might have been an issue in libsass, or something we fixed in a different issue?

**Closed** 2015-09-01 14:28 UTC
Labels: can't reproduce
