### ISSUE TITLE
susy-breakpoint not changing context

### ISSUE THREAD

**Issue by sabaeus** [ericam/susy#428] opened 2015-02-01 22:46 UTC
For some reason, susy-breakpoint is not changing context. If I use this code:

    @include susy-breakpoint(960px, 12) { 
        @include span(2 last); 
    }

I get this output:

    .sidebar2 {
      margin-top: 5vh;
      margin-bottom: 5vh;
      background: rgba(250, 231, 179, 0.8);
      width: 47.36842%;
      float: left;
      margin-left: 52.63158%;
      margin-right: -100%;
    }

With this result: 
![screen shot 2015-02-01 at 2 26 29 pm](https://cloud.githubusercontent.com/assets/5056749/5994234/2cc44802-aa20-11e4-9490-9864beb8d356.png)

But then if I use a normal breakpoint together with the nested mixin, like so: 

    @include breakpoint(960px) {
        @include nested(12) {
            @include span(2 last);
	 }
    }

I get this output:

    @media (min-width: 960px) {
        .sidebar2 {
            width: 15.25424%;
            float: left;
            margin-left: 84.74576%;
            margin-right: -100%;
        }
    }
And this result:
![screen shot 2015-02-01 at 2 25 41 pm](https://cloud.githubusercontent.com/assets/5056749/5994240/3f3237d8-aa20-11e4-98fb-d1d6390b80cb.png)

Global settings in both cases are set to:
    $susy: (
        columns: 4,
        global-box-sizing: border-box,
        output: isolate,
        debug: (image: show)
    );

I have both susy and breakpoint required in config.rb, and imported into the sass file. Any idea what's causing this?

**Comment by ericam** [comment] 2015-02-02 22:19
Sorry, I can't recreate this error with the information given (see [sassmeister demo](http://sassmeister.com/gist/3462d805c2a4e911cb23) showing same results from both inputs). There must be some other code involved? Can you try to track it down a bit more? What does `@debug susy-get(columns)` show inside each of your examples (debug results should be shown in the command line)?

**Comment by sabaeus** [comment] 2015-02-03 02:07
I figured out part of the problem. Using both susy-breakpoint and breakpoint with a nested mixin results in the same css *in sassmeister*. But the output css I get on my local is different. The difference is that susy-breakpoint is not generating the `@media` queries I need to set the new display.

Using `@debug susy-get(columns)`: `/.../.../scss/styles.scss:33 DEBUG: 4`

Which seems to corroborate the above about susy-breakpoint not setting `@media` queries. I'm unclear on why, but assume I improperly set something up.

**Comment by ericam** [comment] 2015-02-05 17:50
The value of `susy-get(columns)` doesn't actually speak to the lack of `@media` — the former is part of Susy's context in Sass (pre-processed) and the later is part of the CSS output (processed by the browser). I don't see it in what you posted initially, but many people get confused by the difference between those contexts. For example:

```scss
// This will not do anything at all.
@include breakpoint(960px) {
  $susy: (columns: 12);
}
```

You can't "change the number of columns at a breakpoint" exactly — because the variable exists in Sass, and the breakpoint exists in the browser. All you can do is change *both the media-query and the variable* for the same block of code (what `susy-breakpoint` does).

```
@include susy-breakpoint(960px, 12) {
  // code inside this block uses the new column setting,
  // and gets output inside a media-query.
}

@include breakpoint(960px) {
  // code in here still uses the global 4-column settings.
  // this media-query is not aware of the previous media-query.
}
```

I'm not sure if that's relevant to your issue?

**Comment by ericam** [comment] 2015-02-05 17:51
The value of `susy-get(columns)` doesn't actually speak to the lack of `@media` — the former is part of Susy's context in Sass (pre-processed) and the later is part of the CSS output (processed by the browser). I don't see it in what you posted initially, but many people get confused by the difference between those contexts. For example:

```scss
// This will not do anything at all.
@include breakpoint(960px) {
  $susy: (columns: 12);
}
```

You can't "change the number of columns at a breakpoint" exactly — because the variable exists in Sass, and the breakpoint exists in the browser. All you can do is change *both the media-query and the variable* for the same block of code (what `susy-breakpoint` does).

```
@include susy-breakpoint(960px, 12) {
  // code inside this block uses the new column setting,
  // and gets output inside a media-query.
}

@include breakpoint(960px) {
  // code in here still uses the global 4-column settings.
  // this media-query is not aware of the previous media-query.
}
```

I'm not sure if that's relevant to your issue?

**Comment by sabaeus** [comment] 2015-02-06 01:46
It is, but my problem remains the same: susy-breakpoint does not convert to the appropriate css on my local. It does not set a new column setting, and it does not set a media query. It essentially does nothing. 

    @include susy-breakpoint(960px, 12) {
    // this outputs neither media query or new column setting
    }

But then this works:

    @include breakpoint(960px) {
        @include nested(12) {
            @include span(2 at 11);
            // this outputs a media query and a new column setting
        }
    }

Both should be producing the same css. And in the sassmeister demos, they do. But on my machine, they don't. My question is: why?

**Comment by webmasterpf** [comment] 2015-03-11 15:26
I think i get the same error, because breakpoint changing css is not always applied.For example:
` @include susy-breakpoint($desktop, 12) {/*    //Dimensions pour les pc*/
         .headHaut {
             .logoHead { 
                @include span(3 of $desktopcol);
             }
             .menuImg {
                @include span(9 of $desktopcol last);
                 padding-top: 1em;
             }
         }
         .headBas {
            
             .site-slogan{@include span(7 of $desktopcol);}
             .headSearch{@include span(5 of $desktopcol last);}
             .menuHead{}
         } 
     }`

produce css like : 
`media="all"
@media (min-width: 700px)
#header .headBas .site-slogan {
width: 14.45em;
float: left;
margin-right: 1em;
}
nodemedia="all"
@media (min-width: 950px)
#header .headBas .site-slogan {
width: 35.05em;
float: left;
margin-right: 1em;`

but it's the first width that is applied ...
another thing it's in chrome F12 : one time i get the file-name.scss and another the compiled css file..crazy

**Comment by ericam** [comment] 2015-09-01 17:49
You've shown one use of `susy-breakpoint` and two different output blocks. I'm not sure what I'm supposed to be looking at. I also don't know what `$desktop` and `$desktopcol` represent. I'm not able to reproduce any bugs here. Closing, unless someone can show me code that breaks consistently.

**Closed by ericam** 2015-09-01 17:49 UTC
