### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by haydenhancock** [ericam/susy#433] opened 2015-02-05 04:21 UTC
I am trying to use susy with a Node.js application. I installed susy using the following command:

npm install --save-dev susy

I didn't get any errors when installed with the latest version (2.2.2), however, when I try to require susy in my Gulpfile.js, I get an error: SyntaxError: Unexpected token ILLEGAL.

I am rather new to Node.js so any help would be appreciated.

**Comment by aaronagray** [comment] 2015-02-05 12:31
Hi Hayden, It sounds like something else may be going on. I suspect there is a syntax error in the Gulpfile. Do you have a link the the repo where you installed this?

**Comment by haydenhancock** [comment] 2015-02-05 14:14
@aaronagray Thanks for the quick reply. I don't think it's an issue in the Gulpfile because I am doing the same thing I did to get Bourbon and Neat to work. In my Gulpfile I have:

`var susy = required('susy');`

In my main stylesheet I have:

`import 'susy';`

**Comment by haydenhancock** [comment] 2015-02-05 17:47
I tried it again with a new project: Here is my setup:

package.json
`{
  "name": "test3",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Hayden Hancock",
  "license": "ISC",
  "devDependencies": {
    "gulp": "^3.8.10",
    "gulp-sass": "^1.3.2",
    "node-sass": "^2.0.0-beta",
    "susy": "^2.2.2"
  }
}
`

gulpfile.js
`var gulp = require('gulp');
var sass = require('gulp-sass');
var susy = require('susy');

gulp.task('default', function() {
  //
});

gulp.task('sass', function(){
  gulp.src('src/scss/*.scss')
    .pipe(sass())
    .pipe(gulp.dest('dist/css'));
})
`

test.scss
`@import 'susy';
`

**Comment by aaronagray** [comment] 2015-02-05 18:23
Thanks for the update. Will you post the full terminal logs before and including the error? I don't use gulp personally, so some more context would be helpful.

**Comment by haydenhancock** [comment] 2015-02-05 18:34
@aaronagray The output is posted above.

**Comment by aaronagray** [comment] 2015-02-05 19:25
Thanks. I'm not sure by looking at this, but my guess is the import path needs to be adjusted. Will you push the `test3 `repo to github so I can try to reproduce this locally?

**Comment by thesublimeobject** [comment] 2015-02-06 22:10
@haydenhancock I have tried several different methods of import, and I am getting some similar errors. At one point I got it working by getting a little hack-y and adding an index.js to the node-module, then feeding the includePaths for where _susy.scss was located. In my gulp file I used susy.includePaths to include susy in the sass path as an included directory. All the being said, I messed around with it some more, and now it isn't working again. BUT, something like that should work. Given the lack of documentation, I'm not sure the best answer to give you.

**Comment by haydenhancock** [comment] 2015-02-09 14:37
@thesublimeobject Well, glad I am not the only one. I was going to play around with including the susy (includePaths) today to see if I could get it working. From my understanding, or at least according to the node-sass documentation, includePaths is an array. I've tried to pass multiple objects into this before but was unsuccessful. I am sure it's because I did it wrong though. I'll report back when I have additional information.

**Comment by thesublimeobject** [comment] 2015-02-09 16:07
@haydenhancock This is how I have multiple appendages to my current sass setup. It works with Neat (which I am using in the interim) because Neat has includePaths set up in the npm module itself. You might want to look at how they have it set up in the index.js. That is the kind of logic I followed when getting it to work. Here is my sass task for gulp:

gulp         = require('gulp')
browserSync  = require('browser-sync')
sass         = require('gulp-sass')
sourcemaps   = require('gulp-sourcemaps')
handleErrors = require('../util/handleErrors')
config       = require('../config').sass
autoprefixer = require('gulp-autoprefixer')
neat 		 = require('node-neat').includePaths
modal		 = require('kbd-modal').includePaths

`gulp.task 'sass', ->
	return gulp.src('styl/src/screen.scss')
		.pipe(sourcemaps.init())
		.pipe(sass
			sourceComments: 'map'
			imagePath: '/img'
			errLogToConsole: true
			includePaths: ['sass'].concat(neat).concat(modal)
		)
		.pipe(autoprefixer
			browsers: ['last 2 version'] 
		)
		.pipe(sourcemaps.write())
		.on('error', handleErrors)
		.pipe(gulp.dest(config.dest))
		.pipe(browserSync.reload({stream:true}))`

**Comment by haydenhancock** [comment] 2015-02-09 16:16
@thesublimeobject Thanks for the Gulpfile.js example. I will play around with it to see if I can get it to work with Susy!

**Comment by ericam** [comment] 2015-08-27 22:34
Has this been resolved? Marking as closed, unless there is still an issue?

**Closed by ericam** 2015-08-27 22:34 UTC

**Comment by joakim1** [comment] 2015-09-18 14:19
I'm getting this too. Screenshot: http://prntscr.com/8hqd9b
